### ISSUE TITLE
implement pwd

### ISSUE THREAD

**Issue by matthewjohnjamieson** [matthewjohnjamieson/tsh#4]
print working directory. I'm sure there are some built in functions in C for this we can use.

**Comment by JMillaCS** [comment]
Are we allowed to use built in functions? Kind of sounded like he would like for us to implement these functionalities on our own.

**Comment by matthewjohnjamieson** [comment]
So the way I understand it is: we can use the built in C functions like realpath() and so on. But we can't just call built in bash functions using an exec like cd or pwd

**Comment by JMillaCS** [comment]
so,
#define _POSIX_C_SOURCE 200112L
#define _ISOC99_SOURCE
#define __EXTENSIONS__
#define _XOPEN_SOURCE 600

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <stdlib.h>
#include <unistd.h>
 
/*
*#define PATH_MAX 
*not sure if this is how one exactly defines PATH_MAX
*/

//This method assumes you're sending it the filename in the form of a char*, prints the current working //directory.
//Returns -1 upon failure, returns 0 on success.

int pwd(char *filename) {
     char path[PATH_MAX];
     memset(path, '\0', sizeof(char) * PATH_MAX);

     if(realpath(filename, path) == NULL) {
        fprintf(stderr, "realpath() failed: %s\n", strerror(errno));
        return -1; //path failed
    }
    printf("%s\n", path);
    return 0; //path successful
}

**Comment by JMillaCS** [comment]
Sorry I took so long, I began doing the realpath() then I psyched  myself out and started doing getcwd(). Where maybe we could use getcwd(), but it does it for the file it's running in. The code I just sent is probably not perfect by any means, but it's an idea. Please let me know what you think guys!

**Comment by matthewjohnjamieson** [comment]
So I just sent you an invitation to be a collaborator on this project, so now you can just make a branch and put your version of the code into that so I can run in and merge it etc.
